spring:
  application:
    name: product
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: admin123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mmall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
#      open-in-view: true
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
